# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-06-08 18:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='time',
            name='Mascote',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
