# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-06-10 18:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_jogo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jogo',
            name='Resultado',
            field=models.CharField(max_length=30),
        ),
    ]
