# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-06-10 18:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20180610_1510'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='time_jogador',
            name='Jogador',
        ),
        migrations.RemoveField(
            model_name='time_jogador',
            name='Time',
        ),
        migrations.AddField(
            model_name='time',
            name='Jogadores',
            field=models.ManyToManyField(to='blog.Jogador'),
        ),
        migrations.DeleteModel(
            name='Time_Jogador',
        ),
    ]
